

###get all
GET http://localhost:3000/todos

###post
POST http://localhost:3000/todos/new
Content-Type: application/json

{
    "text": "asdasd gwapo"
}

###delete
DELETE http://localhost:3000/todos/delete/6603d7bc11817a0560e54dfb

###getupdate
GET http://localhost:3000/todos/complete/6603c129c73ec0697c2b793b